### ISSUE TITLE
多次提示 Waiting for a blocking GC Alloc，感觉像是内存溢出了

### ISSUE THREAD

**Issue by coderlfm** [mjl0602/flutter_tiktok#45]
我把这个主页中复制到我的项目中，虽然能够播放，但是播放了一会就会多次提示下面的报错，期中一次导致应用闪退， 我是在 Getx 中使用的

```dart
I/o.learn_englis(25725): Clamp target GC heap from 517MB to 512MB
I/chatty  (25725): uid=10150(com.liufengmao.learn_english) HeapTaskDaemon identical 5 lines
2
I/o.learn_englis(25725): Clamp target GC heap from 517MB to 512MB
I/chatty  (25725): uid=10150(com.liufengmao.learn_english) HeapTaskDaemon identical 16 lines
I/o.learn_englis(25725): Clamp target GC heap from 517MB to 512MB
I/o.learn_englis(25725): Background young concurrent copying GC freed 24(872B) AllocSpace objects, 0(0B) LOS objects, 0% free, 511MB/512MB, paused 9.007ms total 14.951ms
I/o.learn_englis(25725): Clamp target GC heap from 517MB to 512MB
I/chatty  (25725): uid=10150(com.liufengmao.learn_english) HeapTaskDaemon identical 2 lines
3
I/o.learn_englis(25725): Clamp target GC heap from 517MB to 512MB
I/chatty  (25725): uid=10150(com.liufengmao.learn_english) HeapTaskDaemon identical 16 lines
2
I/o.learn_englis(25725): Clamp target GC heap from 517MB to 512MB
I/chatty  (25725): uid=10150(com.liufengmao.learn_english) HeapTaskDaemon identical 16 lines
I/o.learn_englis(25725): Clamp target GC heap from 517MB to 512MB
I/o.learn_englis(25725): Waiting for a blocking GC Alloc
2
I/o.learn_englis(25725): Starting a blocking GC Alloc
I/o.learn_englis(25725): Clamp target GC heap from 517MB to 512MB
I/o.learn_englis(25725): Alloc concurrent copying GC freed 294(42KB) AllocSpace objects, 0(0B) LOS objects, 0% free, 511MB/512MB, paused 276us total 18.528ms
E/ExoPlayerImplInternal(25725): Playback error
E/ExoPlayerImplInternal(25725):   com.google.android.exoplayer2.ExoPlaybackException: Source error
E/ExoPlayerImplInternal(25725):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:580)
E/ExoPlayerImplInternal(25725):       at android.os.Handler.dispatchMessage(Handler.java:103)
E/ExoPlayerImplInternal(25725):       at android.os.Looper.loop(Looper.java:214)

```

**Comment by techistoner** [comment]
你控制器没释放掉 仔细看下作者的释放
